# Generated by Django 5.2.3 on 2025-06-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avilable',
            new_name='available',
        ),
    ]
